import { gql } from '@apollo/client'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import client from '../apollo-client'
import styles from '../styles/Home.module.css'
export const GET_POSTS = gql`
  query GetPosts {
    posts {
      edges {
        node {
          id
          title
          author {
            node {
              firstName
              lastName
              avatar {
                url
              }
            }
          }
          excerpt(format: RENDERED)
          slug
          content(format: RENDERED)
          featuredImage {
            node {
              title
              sourceUrl
            }
          }
        }
      }
    }
  }
`

export default function Home({ data }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>WP + GraphQL React Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {data && (
        <main className={styles.main}>
          <h1 className={styles.title}>Posts</h1>

          <div className={styles.grid}>
            {data?.posts?.edges?.map((item) => (
              <Link href={`/post/${item?.node?.slug}`} key={item?.node?.id}>
                <div className={styles.card}>
                  <h2>{item?.node?.title}</h2>
                  <p
                    dangerouslySetInnerHTML={{ __html: item?.node?.content }}
                  />
                </div>
              </Link>
            ))}
          </div>
        </main>
      )}

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export async function getStaticProps({ preview = false }) {
  const { data } = await client.query({ query: GET_POSTS })
  return {
    props: { data, preview },
  }
}
